services:
  web:
    build: .
    ports: 
      - "5000:80"
    volumes:
      - .:/app
    depends_on:
      - db
    env_file:
      - ./.env
    networks:
      - python_rest_network
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=myapp
    ports:
      - "5432:5432" 
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - python_rest_network

networks:
  python_rest_network:  
    driver: bridge

volumes:
  postgres_data: